# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.4]

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY_EZE }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL_EZE }}
          usedocker: true
        env:
          HD_DD_API_KEY: ${{ secrets.DD_API_KEY }}
          HD_NODE_ENV: prod
          HD_INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
          HD_MNEMONIC: ${{secrets.MNEMONIC}}
          HD_PAYMENTS_SERVICE_API_KEY: ${{ secrets.PAYMENTS_SERVICE_API_KEY }}
